[package]
name = "procrastinate"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "procrastinate"

[dependencies]
serde = "1.0.138"
url = { version = "2.2.2", features = ["serde"] }
uuid = { version = "1.1.2", features = ["serde"] }
