//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "enum_attachment_type"
)]
pub enum EnumAttachmentType {
    #[sea_orm(string_value = "File")]
    File,
    #[sea_orm(string_value = "Image")]
    Image,
    #[sea_orm(string_value = "Preview")]
    Preview,
}
